network = 4

db_path = "cairo_db"
db_cache = 1
db_max_open_files = 10

# cairoVM
mock_vm = false
max_vms = 1000000
max_vm_queue = 1000000
log_level = 1
colour = true

# ETH L1
enable_l1 = false
eth_client_address = "https://sepolia.infura.io/v3/"

sequencer_addr = "0x46a89ae102987331d369645031b49c27738ed096f2789c24449966da4c6de6b"
skip_charge_fee = true
skip_validate = false
err_on_revert = true

#  L2 eth client configs
enable_l2  = false
chain_id = 11155111
gas_limit = 300000
eth_private_key = ""

# starknet RPC
enable_starknet_rpc = true
starknet_host = "0.0.0.0"
starknet_port = "9091"

# pprof
enable_pprof = true
pprof_addr = "localhost:8081"

[genesis_classes]
# ClassHash -> ContractClass FilePath
# No validation account class
0x0279d77db761fba82e0054125a6fdb5f6baa6286fa3fb73450cc44d193c2d37f = "./conf/genesis/NoValidateAccount.json"
# No validataion account class hash cairo 1
0x02f99bf9799ada84cd5ac0d0fe36b9d8f65efcb377cd2e8cf8309ad2daf15e4b = "./conf/genesis/NoValidateAccountCairoOne.json"
# Argent account class hash
0x06f0d6f6ae72e1a507ff4b65181291642889742dbf8f1a53e9ec1c595d01ba7d = "./conf/genesis/ArgentAccount.json"

# Braavos account class hash
0x2c2b8f559e1221468140ad7b2352b1a5be32660d0bf1a3ae3a054a4ec5254e4 = "./conf/genesis/BraavosAccount.json"

# Braavos account base implementation class hash
0x5aa23d5bb71ddaa783da7ea79d405315bafa7cf0387a74f4593578c3e9e6570 = "./conf/genesis/BraavosAccountBaseImpl.json"
# Braavos account call aggregator class hash
0x07db5c2c2676c2a5bfc892ee4f596b49514e3056a0eee8ad125870b4fb1dd909 = "./conf/genesis/BraavosCallAggregator.json"
# Braavos proxy class hash
0x3131fa018d520a037686ce3efddeab8f28895662f019ca3ca18a626650f7d1e = "./conf/genesis/BraavosProxy.json"


# 	Openzeppelin account class hash
0x006280083f8c2a2db9f737320d5e3029b380e0e820fe24b8d312a6a34fdba0cd = "./conf/genesis/OpenzeppelinAccount.json"

# ERC20 class hash
0x0372ee6669dc86563007245ed7343d5180b96221ce28f44408cff2898038dbd4 = "./conf/genesis/ERC20.json"

# ERC721 class hash
0x077cc28ed3c661419fda16bf120fb81f1f8f28617f5543b05a86d63b0926bbf4 = "./conf/genesis/ERC721.json"

# Universal deployer class hash
0x07b3e05f48f0c69e4a65ce5e076a66271a527aff2c34ce1083ec6e1526997a69 = "./conf/genesis/UniversalDeployer.json"

# Argent Cairo 1 Account
0x01a736d6ed154502257f02b1ccdf4d9d1089f80811cd6acad48e6b6a9d1f2003 = "./conf/genesis/ArgentAccountCairoOne.json"

# OpenZepplin Cairo 1 Account
0x04c6d6cf894f8bc96bb9c525e6853e5483177841f7388f74a46cfda6f028c755 = "./conf/genesis/OpenZeppelinAccountCairoOne.sierra.json"

[genesis_contracts]
# contract address -> class hash
# No Validation Account
0x1 = "0x0279d77db761fba82e0054125a6fdb5f6baa6286fa3fb73450cc44d193c2d37f"
# Argent Account, need private key
0x2 = "0x06f0d6f6ae72e1a507ff4b65181291642889742dbf8f1a53e9ec1c595d01ba7d"
# Openzeppelin Account, need private key
0x3 = "0x006280083f8c2a2db9f737320d5e3029b380e0e820fe24b8d312a6a34fdba0cd"
# No Validation Account (cairo 1)
0x4 = "0x02f99bf9799ada84cd5ac0d0fe36b9d8f65efcb377cd2e8cf8309ad2daf15e4b"

0x1111 = "0x04c5efa8dc6f0554da51f125d04e379ac41153a8b837391083a8dc3771a33388"
0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d00 = "0x0372ee6669dc86563007245ed7343d5180b96221ce28f44408cff2898038dbd4"
0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d02 = "0x077cc28ed3c661419fda16bf120fb81f1f8f28617f5543b05a86d63b0926bbf4"
0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7 = "0x0372ee6669dc86563007245ed7343d5180b96221ce28f44408cff2898038dbd4"
0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf = "0x07b3e05f48f0c69e4a65ce5e076a66271a527aff2c34ce1083ec6e1526997a69"


# ERC20_name
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x341c1bdfd89f69748aa00b5742b03adbffd79b8e80cab5c50d91cd8c2a79be1"
value = "0x4574686572"

# ERC20_symbol
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x0b6ce5410fca59d078ee9b2a4371a9d684c530d697c64fbef0ae6d5e8f0ac72"
value = "0x455448"

# ERC20_decimals
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x1f0d4aa99431d246bac9b8e48c33e888245b15e9678f64f9bdfc8823dc8f979"
value = "0x12"

# ERC20_balances(0x1).low
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x7b62949c85c6af8a50c11c22927f9302f7a2e40bc93b4c988415915b0f97f09"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x1).high
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x7b62949c85c6af8a50c11c22927f9302f7a2e40bc93b4c988415915b0f97f0a"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x2).low
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x1d8bbc4f93f5ab9858f6c0c0de2769599fb97511503d5bf2872ef6846f2146f"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x2).high
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x1d8bbc4f93f5ab9858f6c0c0de2769599fb97511503d5bf2872ef6846f21470"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x3).low
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x262e096a838c0d8f34f641ff917d47d7dcb345c69efe61d9ab6b675e7340fc6"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x3).high
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x262e096a838c0d8f34f641ff917d47d7dcb345c69efe61d9ab6b675e7340fc7"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x4).low
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x45abe05a3e7fb0c2ae1fa912be22a7dbc4832915e00562e2783dee710b9e4bc"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x4).high
[[genesis_storages]]
contract_address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"
key = "0x45abe05a3e7fb0c2ae1fa912be22a7dbc4832915e00562e2783dee710b9e4bd"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x1).low
[[genesis_storages]]
contract_address = "0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d00"
key = "0x7b62949c85c6af8a50c11c22927f9302f7a2e40bc93b4c988415915b0f97f09"
value = "0xffffffffffffffffffffffffffffffff"

# ERC20_balances(0x1).high
[[genesis_storages]]
contract_address = "0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d00"
key = "0x7b62949c85c6af8a50c11c22927f9302f7a2e40bc93b4c988415915b0f97f0a"
value = "0xffffffffffffffffffffffffffffffff"

# _signer
[[genesis_storages]]
contract_address = "0x2"
key = "0x1ccc09c8a19948e048de7add6929589945e25f22059c7345aaf7837188d8d05"
value = "0x3603a2692a2ae60abb343e832ee53b55d6b25f02a3ef1565ec691edc7a209b2"

# Account_public_key
[[genesis_storages]]
contract_address = "0x3"
key = "0x1379ac0624b939ceb9dede92211d7db5ee174fe28be72245b0a1a2abd81c98f"
value = "0x3603a2692a2ae60abb343e832ee53b55d6b25f02a3ef1565ec691edc7a209b2"

# Ownable_owner
[[genesis_storages]]
contract_address = "0x040e59c2c182a58fb0a74349bfa4769cbbcba32547591dd3fb1def8623997d02"
key = "0x2bd557f4ba80dfabefabe45e9b2dd35db1b9a78e96c72bc2b69b655ce47a930"
value = "0x1"





